// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBPorSynFSX-HjaqqRM6qlTWILn1ISgk0',
    appId: '1:240988851168:web:509c1b57a714610d5db985',
    messagingSenderId: '240988851168',
    projectId: 'task-4d162',
    authDomain: 'task-4d162.firebaseapp.com',
    storageBucket: 'task-4d162.appspot.com',
    measurementId: 'G-29QKLF1VC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqZ_K4M2AtTNDQp8WqJx4tCFwdqUttZio',
    appId: '1:240988851168:android:47cab7dd662217f55db985',
    messagingSenderId: '240988851168',
    projectId: 'task-4d162',
    storageBucket: 'task-4d162.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc9wKrxDggkwy8CZV1JJFHvX6dyFXCmxM',
    appId: '1:240988851168:ios:6ebdbb3efd5f86ac5db985',
    messagingSenderId: '240988851168',
    projectId: 'task-4d162',
    storageBucket: 'task-4d162.appspot.com',
    iosClientId: '240988851168-liu6a8shaing7r90jh9aepdcu1afsonb.apps.googleusercontent.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc9wKrxDggkwy8CZV1JJFHvX6dyFXCmxM',
    appId: '1:240988851168:ios:6ebdbb3efd5f86ac5db985',
    messagingSenderId: '240988851168',
    projectId: 'task-4d162',
    storageBucket: 'task-4d162.appspot.com',
    iosClientId: '240988851168-liu6a8shaing7r90jh9aepdcu1afsonb.apps.googleusercontent.com',
    iosBundleId: 'com.example.task',
  );
}
